services:
  app:
    environment:
      - MONGODB_HOST=${EXTERNAL_MONGODB_HOST:-localhost}
      - MONGODB_PORT=${EXTERNAL_MONGODB_PORT:-27017}
      - MONGODB_DATABASE=${EXTERNAL_MONGODB_DATABASE:-rpger}
      - MONGODB_USERNAME=${EXTERNAL_MONGODB_USERNAME:-}
      - MONGODB_PASSWORD=${EXTERNAL_MONGODB_PASSWORD:-}
      - MONGODB_CONNECTION_STRING=${EXTERNAL_MONGODB_CONNECTION_STRING:-}
      - CHROMA_HOST=${EXTERNAL_CHROMA_HOST:-localhost}
      - CHROMA_PORT=${EXTERNAL_CHROMA_PORT:-8000}
      - CHROMA_BASE_URL=${EXTERNAL_CHROMA_BASE_URL:-}
      - SETUP_MODE=external